using Newtonsoft.Json;
using System;
using System.Collections.Generic;
using System.IO;
using ValheimBakaLoader.Tools.Logging;
using ValheimBakaLoader.Tools.Models;

namespace ValheimBakaLoader.Tools
{
    public interface IModScanner
    {
        /// <summary>
        /// Scans a BepInEx plugins directory for installed Thunderstore-style mods.
        /// Read-only; never writes to disk.
        /// </summary>
        List<InstalledMod> ScanPlugins(string pluginsDirectory);
    }

    /// <summary>
    /// Scans a local BepInEx <c>plugins</c> directory for installed mods, deriving
    /// each mod's identity from its <c>Author-ModName</c> folder name and its
    /// version from the folder's <c>manifest.json</c>. Purely read-only: it does
    /// not download, install, move, or modify any files.
    /// </summary>
    public class ModScanner : IModScanner
    {
        private const string ManifestFileName = "manifest.json";
        private const string UnknownVersion = "unknown";

        /// <summary>
        /// Plugin folders that are managed by BakaLoader itself (or auto-generated by a
        /// BepInEx patcher) rather than user-installed Thunderstore mods. These are hidden
        /// from the mods list so users can't accidentally update/remove them:
        /// - BakaLoaderKillAll / BakaLoaderSpawnHelper / BakaLoaderItemIndexer /
        ///   BakaLoaderCommander: bundled companion plugins auto-installed by their
        ///   installers on server start.
        /// - MMHOOK: generated by ValheimModding-HookGenPatcher on each game launch;
        ///   it is game-version-specific and never updated via Thunderstore directly.
        /// </summary>
        private static readonly HashSet<string> CompanionFolderNames = new(System.StringComparer.OrdinalIgnoreCase)
        {
            "BakaLoaderKillAll",
            "BakaLoaderSpawnHelper",
            "BakaLoaderItemIndexer",
            "BakaLoaderCommander",
            "BakaLoaderMaxPlayers",
            "MMHOOK",
        };

        /// <summary>True when a plugins-dir folder name is an app-managed companion plugin.</summary>
        public static bool IsCompanionFolder(string folderName) =>
            !string.IsNullOrWhiteSpace(folderName) && CompanionFolderNames.Contains(folderName);

        /// <summary>
        /// Patcher folders that are part of the framework or auto-generate other content, never a
        /// user-installed mod anyone should list or remove:
        /// - denikson-BepInExPack_Valheim: the BepInEx framework itself.
        /// - ValheimModding-HookGenPatcher: generates the MMHOOK assemblies each launch.
        /// The "patchers" folder is shared across every isolated instance via a junction, so
        /// removing one of these would break the framework for all servers at once.
        /// </summary>
        private static readonly HashSet<string> PatcherProtectedNames = new(System.StringComparer.OrdinalIgnoreCase)
        {
            "denikson-BepInExPack_Valheim",
            "ValheimModding-HookGenPatcher",
        };

        /// <summary>True when a patchers-dir folder name is a framework or auto-generated patcher.</summary>
        public static bool IsProtectedPatcher(string folderName) =>
            !string.IsNullOrWhiteSpace(folderName) && PatcherProtectedNames.Contains(folderName);

        private readonly IApplicationLogger Logger;

        public ModScanner(IApplicationLogger logger)
        {
            Logger = logger;
        }

        public List<InstalledMod> ScanPlugins(string pluginsDirectory)
        {
            var results = new List<InstalledMod>();

            if (string.IsNullOrWhiteSpace(pluginsDirectory) || !Directory.Exists(pluginsDirectory))
            {
                Logger.Warning("Mod scan skipped: plugins directory does not exist: {0}", pluginsDirectory ?? "<null>");
                return results;
            }

            Logger.Information("Scanning for installed mods in: {0}", pluginsDirectory);

            // Folder name -> entry, so a mod that ships both a plugin and a patcher merges into
            // one row (its PatcherDirectory set) instead of listing twice.
            var byFolderName = new Dictionary<string, InstalledMod>(StringComparer.OrdinalIgnoreCase);

            foreach (var modDirectory in Directory.EnumerateDirectories(pluginsDirectory))
            {
                var folderName = new DirectoryInfo(modDirectory).Name;
                if (CompanionFolderNames.Contains(folderName))
                {
                    Logger.Debug("Skipping app-managed companion plugin folder: {0}", folderName);
                    continue;
                }

                var mod = TryReadMod(modDirectory);
                if (mod != null)
                {
                    mod.PluginDirectory = modDirectory;
                    results.Add(mod);
                    byFolderName[folderName] = mod;
                }
            }

            // Patcher-type mods install under BepInEx/patchers, a sibling of plugins. Surface
            // them too so they can be seen and removed; this is read-only.
            ScanPatchers(pluginsDirectory, results, byFolderName);

            Logger.Information("Mod scan complete: found {0} installed mod(s).", results.Count);
            return results;
        }

        /// <summary>
        /// Adds patcher-type mods from the sibling <c>patchers</c> directory. A patcher whose
        /// folder name already has a plugins counterpart merges into that entry (PatcherDirectory
        /// set, no second row); a patcher with no plugins counterpart is added as an
        /// <see cref="InstalledMod.IsPatcher"/> row. Framework and auto-generated patchers are
        /// excluded. A no-op when the patchers directory does not exist. Read-only.
        /// </summary>
        private void ScanPatchers(string pluginsDirectory, List<InstalledMod> results,
            Dictionary<string, InstalledMod> byFolderName)
        {
            string patchersDirectory;
            try
            {
                var parent = Directory.GetParent(pluginsDirectory);
                if (parent == null) return;
                patchersDirectory = Path.Combine(parent.FullName, "patchers");
            }
            catch
            {
                return;
            }

            if (!Directory.Exists(patchersDirectory)) return;

            foreach (var patcherDirectory in Directory.EnumerateDirectories(patchersDirectory))
            {
                var folderName = new DirectoryInfo(patcherDirectory).Name;
                if (CompanionFolderNames.Contains(folderName) || PatcherProtectedNames.Contains(folderName))
                {
                    Logger.Debug("Skipping framework or app-managed patcher folder: {0}", folderName);
                    continue;
                }

                // Same mod already seen as a plugin: attach the patcher folder, do not add a row.
                if (byFolderName.TryGetValue(folderName, out var existing))
                {
                    existing.PatcherDirectory = patcherDirectory;
                    continue;
                }

                var mod = TryReadMod(patcherDirectory);
                if (mod != null)
                {
                    mod.PatcherDirectory = patcherDirectory;
                    mod.IsPatcher = true;
                    results.Add(mod);
                    byFolderName[folderName] = mod;
                }
            }
        }

        /// <summary>
        /// Reads a mod's identity and manifest from a folder (a plugins or a patchers subfolder).
        /// The caller sets the directory field (<see cref="InstalledMod.PluginDirectory"/> or
        /// <see cref="InstalledMod.PatcherDirectory"/>) so the same read serves both.
        /// </summary>
        private InstalledMod TryReadMod(string modDirectory)
        {
            var folderName = new DirectoryInfo(modDirectory).Name;
            var (author, modName) = SplitFolderName(folderName);

            var manifestPath = Path.Combine(modDirectory, ManifestFileName);

            // No manifest: this may be a loose-DLL folder. Report it with an unknown
            // version so the UI can still surface it, but prefer manifest-backed data.
            if (!File.Exists(manifestPath))
            {
                Logger.Debug("No manifest.json in folder, reporting as version-unknown: {0}", folderName);
                return new InstalledMod
                {
                    Author = author,
                    ModName = modName,
                    InstalledVersion = UnknownVersion,
                    // No manifest means no declared dependencies; keep the array empty, not null.
                    Dependencies = Array.Empty<string>(),
                };
            }

            try
            {
                var manifestJson = File.ReadAllText(manifestPath);
                var manifest = JsonConvert.DeserializeObject<ThunderstoreManifest>(manifestJson);

                if (manifest == null)
                {
                    Logger.Warning("manifest.json was empty or unparseable, skipping: {0}", folderName);
                    return null;
                }

                // Prefer the manifest "name" when the folder name has no author segment.
                if (string.IsNullOrWhiteSpace(modName) && !string.IsNullOrWhiteSpace(manifest.Name))
                {
                    modName = manifest.Name;
                }

                return new InstalledMod
                {
                    Author = author,
                    ModName = modName,
                    InstalledVersion = string.IsNullOrWhiteSpace(manifest.VersionNumber)
                        ? UnknownVersion
                        : manifest.VersionNumber.Trim(),
                    Website = manifest.WebsiteUrl,
                    Dependencies = ParseDependencyFullNames(manifest.Dependencies),
                };
            }
            catch (JsonException ex)
            {
                Logger.Warning("Malformed manifest.json in '{0}', skipping: {1}", folderName, ex.Message);
                return null;
            }
            catch (IOException ex)
            {
                Logger.Warning("Could not read manifest.json in '{0}', skipping: {1}", folderName, ex.Message);
                return null;
            }
        }

        /// <summary>
        /// Turns Thunderstore manifest dependency strings ("Namespace-Name-Version") into
        /// the depended-on mods' full names ("Namespace-Name"). A namespace and a name carry
        /// no hyphen, so the version is the final hyphen segment and dropping it leaves the
        /// full name. Blank or malformed entries are skipped. Never returns null.
        /// </summary>
        public static string[] ParseDependencyFullNames(string[] dependencies)
        {
            if (dependencies == null || dependencies.Length == 0) return Array.Empty<string>();

            var result = new List<string>();
            foreach (var dependency in dependencies)
            {
                if (string.IsNullOrWhiteSpace(dependency)) continue;

                var trimmed = dependency.Trim();
                var lastHyphen = trimmed.LastIndexOf('-');
                var fullName = lastHyphen > 0 ? trimmed.Substring(0, lastHyphen) : trimmed;
                if (!string.IsNullOrWhiteSpace(fullName)) result.Add(fullName);
            }

            return result.ToArray();
        }

        /// <summary>
        /// Over a set of installed mods, returns the ones that depend on
        /// <paramref name="targetFullName"/>, directly or transitively (a mod that depends on
        /// a mod that depends on the target counts). The result excludes the target itself and
        /// is ordered dependents-first: a mod always appears before any mod it depends on, so
        /// removing the list in order never orphans a still-installed mod midway. A visited set
        /// makes the walk safe against dependency cycles and a widely-depended-on core, so
        /// nothing loops or is listed twice.
        /// </summary>
        public static List<InstalledMod> FindDependents(IEnumerable<InstalledMod> mods, string targetFullName)
        {
            var ordered = new List<InstalledMod>();
            if (mods == null || string.IsNullOrWhiteSpace(targetFullName)) return ordered;

            var list = new List<InstalledMod>();
            foreach (var mod in mods)
                if (mod != null) list.Add(mod);

            // First installed mod for each full name (folder names are unique, but guard anyway).
            var byFullName = new Dictionary<string, InstalledMod>(StringComparer.OrdinalIgnoreCase);
            foreach (var mod in list)
                if (!string.IsNullOrWhiteSpace(mod.FullName) && !byFullName.ContainsKey(mod.FullName))
                    byFullName[mod.FullName] = mod;

            // 1) Transitive dependent set, by reverse reachability from the target: mods whose
            //    dependencies reach the current frontier, growing the frontier each round.
            var dependents = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var frontier = new HashSet<string>(StringComparer.OrdinalIgnoreCase) { targetFullName };
            while (frontier.Count > 0)
            {
                var next = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
                foreach (var mod in list)
                {
                    var name = mod.FullName;
                    if (string.IsNullOrWhiteSpace(name)) continue;
                    if (string.Equals(name, targetFullName, StringComparison.OrdinalIgnoreCase)) continue;
                    if (dependents.Contains(name)) continue;

                    var deps = mod.Dependencies ?? Array.Empty<string>();
                    foreach (var dep in deps)
                    {
                        if (dep != null && frontier.Contains(dep))
                        {
                            dependents.Add(name);
                            next.Add(name);
                            break;
                        }
                    }
                }
                frontier = next;
            }

            if (dependents.Count == 0) return ordered;

            // 2) Order dependents-first with a depth-first post-order over the depends-on graph
            //    restricted to the dependent set, then reversed: post-order lists a mod's
            //    dependencies before the mod, so the reverse lists dependents before what they
            //    depend on. The visited set both dedupes and breaks cycles.
            var visited = new HashSet<string>(StringComparer.OrdinalIgnoreCase);
            var postOrder = new List<string>();

            void Visit(string name)
            {
                if (!visited.Add(name)) return;
                if (byFullName.TryGetValue(name, out var mod))
                {
                    var deps = mod.Dependencies ?? Array.Empty<string>();
                    foreach (var dep in deps)
                        if (dep != null && dependents.Contains(dep)) Visit(dep);
                }
                postOrder.Add(name);
            }

            foreach (var name in dependents) Visit(name);

            for (var i = postOrder.Count - 1; i >= 0; i--)
                if (byFullName.TryGetValue(postOrder[i], out var mod))
                    ordered.Add(mod);

            return ordered;
        }

        /// <summary>
        /// Splits a Thunderstore-style "Author-ModName" folder name on the FIRST
        /// hyphen only: author names never contain a hyphen, but mod names may.
        /// If there is no hyphen, the whole name is treated as the mod name with an
        /// empty author.
        /// </summary>
        private static (string author, string modName) SplitFolderName(string folderName)
        {
            if (string.IsNullOrWhiteSpace(folderName))
            {
                return (string.Empty, string.Empty);
            }

            var hyphenIndex = folderName.IndexOf('-');
            if (hyphenIndex <= 0 || hyphenIndex == folderName.Length - 1)
            {
                return (string.Empty, folderName);
            }

            var author = folderName.Substring(0, hyphenIndex);
            var modName = folderName.Substring(hyphenIndex + 1);
            return (author, modName);
        }

        /// <summary>
        /// Minimal DTO for the subset of Thunderstore <c>manifest.json</c> fields we read.
        /// </summary>
        private class ThunderstoreManifest
        {
            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("version_number")]
            public string VersionNumber { get; set; }

            [JsonProperty("website_url")]
            public string WebsiteUrl { get; set; }

            [JsonProperty("dependencies")]
            public string[] Dependencies { get; set; }
        }
    }
}
