using Newtonsoft.Json;
using System.Collections.Generic;
using System.IO;
using ValheimBakaLoader.Tools.Logging;
using ValheimBakaLoader.Tools.Models;

namespace ValheimBakaLoader.Tools
{
    public interface IModScanner
    {
        /// <summary>
        /// Scans a BepInEx plugins directory for installed Thunderstore-style mods.
        /// Read-only; never writes to disk.
        /// </summary>
        List<InstalledMod> ScanPlugins(string pluginsDirectory);
    }

    /// <summary>
    /// Scans a local BepInEx <c>plugins</c> directory for installed mods, deriving
    /// each mod's identity from its <c>Author-ModName</c> folder name and its
    /// version from the folder's <c>manifest.json</c>. Purely read-only: it does
    /// not download, install, move, or modify any files.
    /// </summary>
    public class ModScanner : IModScanner
    {
        private const string ManifestFileName = "manifest.json";
        private const string UnknownVersion = "unknown";

        /// <summary>
        /// Plugin folders that are managed by BakaLoader itself (or auto-generated by a
        /// BepInEx patcher) rather than user-installed Thunderstore mods. These are hidden
        /// from the mods list so users can't accidentally update/remove them:
        /// - BakaLoaderKillAll / BakaLoaderSpawnHelper / BakaLoaderItemIndexer /
        ///   BakaLoaderCommander: bundled companion plugins auto-installed by their
        ///   installers on server start.
        /// - MMHOOK: generated by ValheimModding-HookGenPatcher on each game launch;
        ///   it is game-version-specific and never updated via Thunderstore directly.
        /// </summary>
        private static readonly HashSet<string> CompanionFolderNames = new(System.StringComparer.OrdinalIgnoreCase)
        {
            "BakaLoaderKillAll",
            "BakaLoaderSpawnHelper",
            "BakaLoaderItemIndexer",
            "BakaLoaderCommander",
            "BakaLoaderMaxPlayers",
            "MMHOOK",
        };

        /// <summary>True when a plugins-dir folder name is an app-managed companion plugin.</summary>
        public static bool IsCompanionFolder(string folderName) =>
            !string.IsNullOrWhiteSpace(folderName) && CompanionFolderNames.Contains(folderName);

        private readonly IApplicationLogger Logger;

        public ModScanner(IApplicationLogger logger)
        {
            Logger = logger;
        }

        public List<InstalledMod> ScanPlugins(string pluginsDirectory)
        {
            var results = new List<InstalledMod>();

            if (string.IsNullOrWhiteSpace(pluginsDirectory) || !Directory.Exists(pluginsDirectory))
            {
                Logger.Warning("Mod scan skipped: plugins directory does not exist: {0}", pluginsDirectory ?? "<null>");
                return results;
            }

            Logger.Information("Scanning for installed mods in: {0}", pluginsDirectory);

            foreach (var modDirectory in Directory.EnumerateDirectories(pluginsDirectory))
            {
                var folderName = new DirectoryInfo(modDirectory).Name;
                if (CompanionFolderNames.Contains(folderName))
                {
                    Logger.Debug("Skipping app-managed companion plugin folder: {0}", folderName);
                    continue;
                }

                var mod = TryReadMod(modDirectory);
                if (mod != null)
                {
                    results.Add(mod);
                }
            }

            Logger.Information("Mod scan complete: found {0} installed mod(s).", results.Count);
            return results;
        }

        private InstalledMod TryReadMod(string modDirectory)
        {
            var folderName = new DirectoryInfo(modDirectory).Name;
            var (author, modName) = SplitFolderName(folderName);

            var manifestPath = Path.Combine(modDirectory, ManifestFileName);

            // No manifest: this may be a loose-DLL folder. Report it with an unknown
            // version so the UI can still surface it, but prefer manifest-backed data.
            if (!File.Exists(manifestPath))
            {
                Logger.Debug("No manifest.json in folder, reporting as version-unknown: {0}", folderName);
                return new InstalledMod
                {
                    Author = author,
                    ModName = modName,
                    InstalledVersion = UnknownVersion,
                    PluginDirectory = modDirectory,
                };
            }

            try
            {
                var manifestJson = File.ReadAllText(manifestPath);
                var manifest = JsonConvert.DeserializeObject<ThunderstoreManifest>(manifestJson);

                if (manifest == null)
                {
                    Logger.Warning("manifest.json was empty or unparseable, skipping: {0}", folderName);
                    return null;
                }

                // Prefer the manifest "name" when the folder name has no author segment.
                if (string.IsNullOrWhiteSpace(modName) && !string.IsNullOrWhiteSpace(manifest.Name))
                {
                    modName = manifest.Name;
                }

                return new InstalledMod
                {
                    Author = author,
                    ModName = modName,
                    InstalledVersion = string.IsNullOrWhiteSpace(manifest.VersionNumber)
                        ? UnknownVersion
                        : manifest.VersionNumber.Trim(),
                    Website = manifest.WebsiteUrl,
                    PluginDirectory = modDirectory,
                };
            }
            catch (JsonException ex)
            {
                Logger.Warning("Malformed manifest.json in '{0}', skipping: {1}", folderName, ex.Message);
                return null;
            }
            catch (IOException ex)
            {
                Logger.Warning("Could not read manifest.json in '{0}', skipping: {1}", folderName, ex.Message);
                return null;
            }
        }

        /// <summary>
        /// Splits a Thunderstore-style "Author-ModName" folder name on the FIRST
        /// hyphen only: author names never contain a hyphen, but mod names may.
        /// If there is no hyphen, the whole name is treated as the mod name with an
        /// empty author.
        /// </summary>
        private static (string author, string modName) SplitFolderName(string folderName)
        {
            if (string.IsNullOrWhiteSpace(folderName))
            {
                return (string.Empty, string.Empty);
            }

            var hyphenIndex = folderName.IndexOf('-');
            if (hyphenIndex <= 0 || hyphenIndex == folderName.Length - 1)
            {
                return (string.Empty, folderName);
            }

            var author = folderName.Substring(0, hyphenIndex);
            var modName = folderName.Substring(hyphenIndex + 1);
            return (author, modName);
        }

        /// <summary>
        /// Minimal DTO for the subset of Thunderstore <c>manifest.json</c> fields we read.
        /// </summary>
        private class ThunderstoreManifest
        {
            [JsonProperty("name")]
            public string Name { get; set; }

            [JsonProperty("version_number")]
            public string VersionNumber { get; set; }

            [JsonProperty("website_url")]
            public string WebsiteUrl { get; set; }

            [JsonProperty("dependencies")]
            public string[] Dependencies { get; set; }
        }
    }
}
